export const PRODUCTS = [
  {
    id: 1,
    productName: "Product 1",
    unit: "box",
    harga: 1035.67,
  },
  {
    id: 2,
    productName: "Product 2",
    unit: "bag",
    harga: 1071.34,
  },
  {
    id: 3,
    productName: "Product 3",
    unit: "bottle",
    harga: 1107.01,
  },
  {
    id: 4,
    productName: "Product 4",
    unit: "pack",
    harga: 1142.68,
  },
  {
    id: 5,
    productName: "Product 5",
    unit: "jar",
    harga: 1178.35,
  },
  {
    id: 6,
    productName: "Product 6",
    unit: "box",
    harga: 1214.02,
  },
  {
    id: 7,
    productName: "Product 7",
    unit: "bag",
    harga: 1249.69,
  },
  {
    id: 8,
    productName: "Product 8",
    unit: "bottle",
    harga: 1285.36,
  },
  {
    id: 9,
    productName: "Product 9",
    unit: "pack",
    harga: 1321.03,
  },
  {
    id: 10,
    productName: "Product 10",
    unit: "jar",
    harga: 1356.7,
  },
  {
    id: 11,
    productName: "Product 11",
    unit: "box",
    harga: 1392.37,
  },
  {
    id: 12,
    productName: "Product 12",
    unit: "bag",
    harga: 1428.04,
  },
  {
    id: 13,
    productName: "Product 13",
    unit: "bottle",
    harga: 1463.71,
  },
  {
    id: 14,
    productName: "Product 14",
    unit: "pack",
    harga: 1499.38,
  },
  {
    id: 15,
    productName: "Product 15",
    unit: "jar",
    harga: 1535.05,
  },
  {
    id: 16,
    productName: "Product 16",
    unit: "box",
    harga: 1570.72,
  },
  {
    id: 17,
    productName: "Product 17",
    unit: "bag",
    harga: 1606.39,
  },
  {
    id: 18,
    productName: "Product 18",
    unit: "bottle",
    harga: 1642.06,
  },
  {
    id: 19,
    productName: "Product 19",
    unit: "pack",
    harga: 1677.73,
  },
  {
    id: 20,
    productName: "Product 20",
    unit: "jar",
    harga: 1713.4,
  },
  {
    id: 21,
    productName: "Product 21",
    unit: "box",
    harga: 1749.07,
  },
  {
    id: 22,
    productName: "Product 22",
    unit: "bag",
    harga: 1784.74,
  },
  {
    id: 23,
    productName: "Product 23",
    unit: "bottle",
    harga: 1820.41,
  },
  {
    id: 24,
    productName: "Product 24",
    unit: "pack",
    harga: 1856.08,
  },
  {
    id: 25,
    productName: "Product 25",
    unit: "jar",
    harga: 1891.75,
  },
  {
    id: 26,
    productName: "Product 26",
    unit: "box",
    harga: 1927.42,
  },
  {
    id: 27,
    productName: "Product 27",
    unit: "bag",
    harga: 1963.09,
  },
  {
    id: 28,
    productName: "Product 28",
    unit: "bottle",
    harga: 1998.76,
  },
  {
    id: 29,
    productName: "Product 29",
    unit: "pack",
    harga: 2034.43,
  },
  {
    id: 30,
    productName: "Product 30",
    unit: "jar",
    harga: 2070.1,
  },
  {
    id: 31,
    productName: "Product 31",
    unit: "box",
    harga: 2105.77,
  },
  {
    id: 32,
    productName: "Product 32",
    unit: "bag",
    harga: 2141.44,
  },
  {
    id: 33,
    productName: "Product 33",
    unit: "bottle",
    harga: 2177.11,
  },
  {
    id: 34,
    productName: "Product 34",
    unit: "pack",
    harga: 2212.78,
  },
  {
    id: 35,
    productName: "Product 35",
    unit: "jar",
    harga: 2248.45,
  },
  {
    id: 36,
    productName: "Product 36",
    unit: "box",
    harga: 2284.12,
  },
  {
    id: 37,
    productName: "Product 37",
    unit: "bag",
    harga: 2319.79,
  },
  {
    id: 38,
    productName: "Product 38",
    unit: "bottle",
    harga: 2355.46,
  },
  {
    id: 39,
    productName: "Product 39",
    unit: "pack",
    harga: 2391.13,
  },
  {
    id: 40,
    productName: "Product 40",
    unit: "jar",
    harga: 2426.8,
  },
  {
    id: 41,
    productName: "Product 41",
    unit: "box",
    harga: 2462.47,
  },
  {
    id: 42,
    productName: "Product 42",
    unit: "bag",
    harga: 2498.14,
  },
  {
    id: 43,
    productName: "Product 43",
    unit: "bottle",
    harga: 2533.81,
  },
  {
    id: 44,
    productName: "Product 44",
    unit: "pack",
    harga: 2569.48,
  },
  {
    id: 45,
    productName: "Product 45",
    unit: "jar",
    harga: 2605.15,
  },
  {
    id: 46,
    productName: "Product 46",
    unit: "box",
    harga: 2640.82,
  },
  {
    id: 47,
    productName: "Product 47",
    unit: "bag",
    harga: 2676.49,
  },
  {
    id: 48,
    productName: "Product 48",
    unit: "bottle",
    harga: 2712.16,
  },
  {
    id: 49,
    productName: "Product 49",
    unit: "pack",
    harga: 2747.83,
  },
  {
    id: 50,
    productName: "Product 50",
    unit: "jar",
    harga: 2783.5,
  },
  {
    id: 51,
    productName: "Product 51",
    unit: "box",
    harga: 2819.17,
  },
  {
    id: 52,
    productName: "Product 52",
    unit: "bag",
    harga: 2854.84,
  },
  {
    id: 53,
    productName: "Product 53",
    unit: "bottle",
    harga: 2890.51,
  },
  {
    id: 54,
    productName: "Product 54",
    unit: "pack",
    harga: 2926.18,
  },
  {
    id: 55,
    productName: "Product 55",
    unit: "jar",
    harga: 2961.85,
  },
  {
    id: 56,
    productName: "Product 56",
    unit: "box",
    harga: 2997.52,
  },
  {
    id: 57,
    productName: "Product 57",
    unit: "bag",
    harga: 3033.19,
  },
  {
    id: 58,
    productName: "Product 58",
    unit: "bottle",
    harga: 3068.86,
  },
  {
    id: 59,
    productName: "Product 59",
    unit: "pack",
    harga: 3104.53,
  },
  {
    id: 60,
    productName: "Product 60",
    unit: "jar",
    harga: 3140.2,
  },
  {
    id: 61,
    productName: "Product 61",
    unit: "box",
    harga: 3175.87,
  },
  {
    id: 62,
    productName: "Product 62",
    unit: "bag",
    harga: 3211.54,
  },
  {
    id: 63,
    productName: "Product 63",
    unit: "bottle",
    harga: 3247.21,
  },
  {
    id: 64,
    productName: "Product 64",
    unit: "pack",
    harga: 3282.88,
  },
  {
    id: 65,
    productName: "Product 65",
    unit: "jar",
    harga: 3318.55,
  },
  {
    id: 66,
    productName: "Product 66",
    unit: "box",
    harga: 3354.22,
  },
  {
    id: 67,
    productName: "Product 67",
    unit: "bag",
    harga: 3389.89,
  },
  {
    id: 68,
    productName: "Product 68",
    unit: "bottle",
    harga: 3425.56,
  },
  {
    id: 69,
    productName: "Product 69",
    unit: "pack",
    harga: 3461.23,
  },
  {
    id: 70,
    productName: "Product 70",
    unit: "jar",
    harga: 3496.9,
  },
  {
    id: 71,
    productName: "Product 71",
    unit: "box",
    harga: 3532.57,
  },
  {
    id: 72,
    productName: "Product 72",
    unit: "bag",
    harga: 3568.24,
  },
  {
    id: 73,
    productName: "Product 73",
    unit: "bottle",
    harga: 3603.91,
  },
  {
    id: 74,
    productName: "Product 74",
    unit: "pack",
    harga: 3639.58,
  },
  {
    id: 75,
    productName: "Product 75",
    unit: "jar",
    harga: 3675.25,
  },
  {
    id: 76,
    productName: "Product 76",
    unit: "box",
    harga: 3710.92,
  },
  {
    id: 77,
    productName: "Product 77",
    unit: "bag",
    harga: 3746.59,
  },
  {
    id: 78,
    productName: "Product 78",
    unit: "bottle",
    harga: 3782.26,
  },
  {
    id: 79,
    productName: "Product 79",
    unit: "pack",
    harga: 3817.93,
  },
  {
    id: 80,
    productName: "Product 80",
    unit: "jar",
    harga: 3853.6,
  },
  {
    id: 81,
    productName: "Product 81",
    unit: "box",
    harga: 3889.27,
  },
  {
    id: 82,
    productName: "Product 82",
    unit: "bag",
    harga: 3924.94,
  },
  {
    id: 83,
    productName: "Product 83",
    unit: "bottle",
    harga: 3960.61,
  },
  {
    id: 84,
    productName: "Product 84",
    unit: "pack",
    harga: 3996.28,
  },
  {
    id: 85,
    productName: "Product 85",
    unit: "jar",
    harga: 4031.95,
  },
  {
    id: 86,
    productName: "Product 86",
    unit: "box",
    harga: 4067.62,
  },
  {
    id: 87,
    productName: "Product 87",
    unit: "bag",
    harga: 4103.29,
  },
  {
    id: 88,
    productName: "Product 88",
    unit: "bottle",
    harga: 4138.96,
  },
  {
    id: 89,
    productName: "Product 89",
    unit: "pack",
    harga: 4174.63,
  },
  {
    id: 90,
    productName: "Product 90",
    unit: "jar",
    harga: 4210.3,
  },
  {
    id: 91,
    productName: "Product 91",
    unit: "box",
    harga: 4245.97,
  },
  {
    id: 92,
    productName: "Product 92",
    unit: "bag",
    harga: 4281.64,
  },
  {
    id: 93,
    productName: "Product 93",
    unit: "bottle",
    harga: 4317.31,
  },
  {
    id: 94,
    productName: "Product 94",
    unit: "pack",
    harga: 4352.98,
  },
  {
    id: 95,
    productName: "Product 95",
    unit: "jar",
    harga: 4388.65,
  },
  {
    id: 96,
    productName: "Product 96",
    unit: "box",
    harga: 4424.32,
  },
  {
    id: 97,
    productName: "Product 97",
    unit: "bag",
    harga: 4459.99,
  },
  {
    id: 98,
    productName: "Product 98",
    unit: "bottle",
    harga: 4495.66,
  },
  {
    id: 99,
    productName: "Product 99",
    unit: "pack",
    harga: 4531.33,
  },
  // {
  //   id: 100,
  //   productName: "Product 100",
  //   unit: "jar",
  //   harga: 4567.0,
  // },
];

export const CUSTOMERS = [
  {
    customerId: 1,
    name: "Budi Santoso",
    email: "budi.santoso@babakanmadang.com",
    phone: "+62-812-3456-7890",
    address: "Restoran Sederhana, Babakan Madang, Bogor",
    customerType: "Restoran"
  },
  {
    customerId: 2,
    name: "Siti Nurhaliza",
    email: "siti.nurhaliza@babakanmadang.com",
    phone: "+62-813-9876-5432",
    address: "Kafe Kopi Nusantara, Babakan Madang, Bogor",
    customerType: "Kafe"
  },
  {
    customerId: 3,
    name: "Ahmad Faisal",
    email: "ahmad.faisal@babakanmadang.com",
    phone: "+62-811-2233-4455",
    address: "Hotel Harmoni, Babakan Madang, Bogor",
    customerType: "Hotel"
  },
  {
    customerId: 4,
    name: "Lilis Suryani",
    email: "lilis.suryani@babakanmadang.com",
    phone: "+62-815-6677-8899",
    address: "Warung Makan Lestari, Babakan Madang, Bogor",
    customerType: "Warung Makan"
  },
  {
    customerId: 5,
    name: "Heri Supriyadi",
    email: "heri.supriyadi@babakanmadang.com",
    phone: "+62-819-3344-5566",
    address: "Restoran Padang Rasa, Babakan Madang, Bogor",
    customerType: "Restoran"
  },
  {
    customerId: 6,
    name: "Dewi Kartika",
    email: "dewi.kartika@babakanmadang.com",
    phone: "+62-817-7788-9900",
    address: "Kafe Santai, Babakan Madang, Bogor",
    customerType: "Kafe"
  },
  {
    customerId: 7,
    name: "Teguh Prasetyo",
    email: "teguh.prasetyo@babakanmadang.com",
    phone: "+62-812-5566-7788",
    address: "Penginapan Asri, Babakan Madang, Bogor",
    customerType: "Penginapan"
  },
  {
    customerId: 8,
    name: "Rina Apriani",
    email: "rina.apriani@babakanmadang.com",
    phone: "+62-816-4455-6677",
    address: "Restoran Ayam Bakar, Babakan Madang, Bogor",
    customerType: "Restoran"
  },
  {
    customerId: 9,
    name: "Eko Saputra",
    email: "eko.saputra@babakanmadang.com",
    phone: "+62-818-1234-5678",
    address: "Kafe D'Bogor, Babakan Madang, Bogor",
    customerType: "Kafe"
  },
  {
    customerId: 10,
    name: "Sri Handayani",
    email: "sri.handayani@babakanmadang.com",
    phone: "+62-814-9876-5432",
    address: "Hotel Amanah, Babakan Madang, Bogor",
    customerType: "Hotel"
  },
  {
    customerId: 11,
    name: "Rahmat Hidayat",
    email: "rahmat.hidayat@babakanmadang.com",
    phone: "+62-822-5678-1234",
    address: "Restoran Nusantara, Babakan Madang, Bogor",
    customerType: "Restoran"
  },
  {
    customerId: 12,
    name: "Maya Anjani",
    email: "maya.anjani@babakanmadang.com",
    phone: "+62-823-4455-6677",
    address: "Kafe Senja Indah, Babakan Madang, Bogor",
    customerType: "Kafe"
  },
  {
    customerId: 13,
    name: "Dimas Pratama",
    email: "dimas.pratama@babakanmadang.com",
    phone: "+62-821-3344-5566",
    address: "Hotel Grand Madang, Babakan Madang, Bogor",
    customerType: "Hotel"
  },
  {
    customerId: 14,
    name: "Rini Marlina",
    email: "rini.marlina@babakanmadang.com",
    phone: "+62-824-2233-1122",
    address: "Warung Tenda Sari, Babakan Madang, Bogor",
    customerType: "Warung Makan"
  },
  {
    customerId: 15,
    name: "Fajar Maulana",
    email: "fajar.maulana@babakanmadang.com",
    phone: "+62-828-5566-7788",
    address: "Restoran Lezat, Babakan Madang, Bogor",
    customerType: "Restoran"
  },
  {
    customerId: 16,
    name: "Fitri Yuliana",
    email: "fitri.yuliana@babakanmadang.com",
    phone: "+62-826-9988-7766",
    address: "Kafe Bukit Hijau, Babakan Madang, Bogor",
    customerType: "Kafe"
  },
  {
    customerId: 17,
    name: "Adi Prasetya",
    email: "adi.prasetya@babakanmadang.com",
    phone: "+62-829-4433-2211",
    address: "Penginapan Lestari, Babakan Madang, Bogor",
    customerType: "Penginapan"
  },
  {
    customerId: 18,
    name: "Lina Astuti",
    email: "lina.astuti@babakanmadang.com",
    phone: "+62-825-5677-3456",
    address: "Warung Rakyat, Babakan Madang, Bogor",
    customerType: "Warung Makan"
  },
  {
    customerId: 19,
    name: "Andi Susanto",
    email: "andi.susanto@babakanmadang.com",
    phone: "+62-818-6677-4455",
    address: "Restoran Mewah, Babakan Madang, Bogor",
    customerType: "Restoran"
  },
  {
    customerId: 20,
    name: "Nina Safitri",
    email: "nina.safitri@babakanmadang.com",
    phone: "+62-813-5544-7788",
    address: "Kafe Malam Ceria, Babakan Madang, Bogor",
    customerType: "Kafe"
  }
];